export const dataProcessor = "Individual, entity or organization that, either personally or through a project, collects, records, organizes, structures, stores, adapts or alters, retrieves, consults, uses, discloses, transmits, disseminates or otherwise makes available, aligns, combines, restricts, erases or destroys data."
export const dataRecipient = "Person to whom the data is disclosed in accordance with a data access agreement either open, controlled or registered. These are usually researchers, research centres or companies who will use the data for further research."
export const dataDonor = "Refers to the individual whom the data is about. Examples of data producer include a researcher, clinician or institution who collected your data. "
export const europe = "It refers to the country members of the European Union and the European Economic Area. The full list of countried belonging to the European Union can be found at: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:European_Economic_Area_(EEA)"
export const directlyIdentifiable = "Information that identifies a specific individual using direct identifiers (name, social insurance number or personal health number."
export const indirectlyIdentifiable = "Information that, in combination with indirect identifiers (date of birth or place of residence), can be reasonable expected to identify a specific individual."
export const coded = "information from which direct identifiers have been removed and have been replaced with a code. Access terms to this code will determine whether the information can identify an individual."
export const anonymized = "Information that has been irrevocably stripped from all direct identifiers."
export const anonymous = "Information that has never been identifiable."
export const publicInformation = "Personal information that has been legally made public, either because it is deemed public by law public or because the person to whom it is associated consented to it being public."
export const federalGovernmentInstitution = "Department or ministry of state of the Government of Canada, any parent Crown corporation or subsidiary of such a corporation."
export const privateCommercial = "A person, association, organization or company who engages in a transaction, act or conduct of a commercial character."
export const fwub = "Organizations devoted to airports; air, highway & railway transportation; banking; broadcasting; canals, pipelines, tunnels, & bridges; some First Nations activities; fisheries; marine shipping, ferry, & port services; telecommunications; uranium; and in the Northwestern Territories, Yukon, & Nunavut."
export const provincial = "Departments, agencies or ministries of state of the provincial governments."
export const mush = "Municipalities and public universities, schools, and hospitals."
export const healthcare = "Doctors, dentists, physiotherapists, genetic counselors, psychologists, and any other professional similarly engaged in activities involving healthcare services."
export const privateNonCommercial = "A person, association, partnership or organization who engages in activities that do not have any commercial character."
